### ISSUE TITLE
Add Next starred channel in notification tray

### ISSUE THREAD

**Issue by PanderMusubi** [rejhgadellaa/icerrr#144]
Please add a menu item in the notification tray for Icerrr with a start icon and text "Next". Upon pressing this, Icerr will start playing the next starred channel. If Icerrr is stopped at the moment and "Next" is pressed, it will go into playing mode. If no channels are starred, this option will not be offered.

**Comment by rejhgadellaa** [comment]
First version rolling out in 0.172, needs some more work to really smooth it out
1. When stream is started, check if it is starred and set 'current playing index' to that channel's index if so
2. What happens when people start editing starred stations while stream is playing...? Worst case: index gets reset to 0?

**Comment by rejhgadellaa** [comment]
Okay the feature is available in 0.174 but I need some feedback on how it now works. So I'll keep this issue open with status_feedback for a while :)
