### ISSUE TITLE
Show time in locked screen

### ISSUE THREAD

**Issue by PanderMusubi** [rejhgadellaa/icerrr#151]
Locked screen shows icon above scrolling track title. The icon is unneeded as it is also shown in notification tray,  so here it can be removed and time and date can be displayed.

**Comment by rejhgadellaa** [comment]
Unfortunately I have no control over how the lock screen appears, this is determined by the ROM you are using. Icerrr just registers itself as a media app that is currently playing music and indicates which media controls it can handle (play/pause, fwd, previous) and album art. 

Android's default behaviour is that it shows the media controls instead of the clock. The app's icon is also placed there automatically, I have no control over that either.
