### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ayhanerdem** [rejhgadellaa/icerrr#165]
Hello

I've an wifi connection but app doesn't work.

![screenshot_2015-02-15-07-19-27](https://cloud.githubusercontent.com/assets/1282695/6202178/4f54446c-b4e3-11e4-8182-b00c948891f9.png)

**Comment by rejhgadellaa** [comment]
Hmm weird. What device + android version are you on?

And could you open the app, go to menu then 'send feedback'? That triggers a log to be sent to me. Just make sure you also send the email with the device info so I can find the correct log

**Comment by ayhanerdem** [comment]
Samsung GT-I9300 and Android 4.3
Menu can't open, 'cause when I select "continue" error message is showing again and again.

**Comment by rejhgadellaa** [comment]
Ok thanks I will have a look. The msg showing over and over again sounds like a definite bug so that should at least be fixed quickly.

**Comment by rejhgadellaa** [comment]
Ah I think I figured out why it won't continue after pressing OK: you probably just installed it and it needs to do some initial setup. For that it needs an internet connection (to download a recent version of the (pre-installed) station database). So that behaviour is as intended.

But why it keeps saying "UNKNOWN" when you clearly have a wifi connection is a bit of a puzzle to me. 

Are you on stock firmware? (Looks like it from the icons in the notification bar but doesn't hurt to ask)

Do you have a mobile plan? If so, could you try running it with mobile data connection instead of wifi?

Anyway, I'll (try to) look into it some more. I don't own a device on Android 4.3 so I can't test if it's related to that :S

**Comment by rejhgadellaa** [comment]
I'm in the process of rolling out an update (0.198) which should classify connection "UNKNOWN" as being connected.. 

Just one quick check: you are running a version of Icerrr you downloaded outside of the Play Store (it has been pulled some time ago, for now I distribute it independently). If you did install it via Play Store, please visit this link and install that version instead: www.rejh.nl/icerrr/

**Comment by rejhgadellaa** [comment]
Update rolling out now, you should be able to install the new version via the link provided above. Please try that and report if it works.

I'll keep this issue open for a bit to further investigate why it's returning UNKNOWN instead of WIFI
