### ISSUE TITLE
Scrobbling support 

### ISSUE THREAD

**Issue by PanderMusubi** [rejhgadellaa/icerrr#207]
Investigate if supporting of scrobbling to Last.FM and Libre.FM is possible. Good reference to develop and test against is https://play.google.com/store/apps/details?id=com.adam.aslfms Note that you don't need to manage scrobbling accounts but only pass on the playing information via an API to a scrobbling app.

**Comment by rejhgadellaa** [comment]
Will look into it. I'm working on a new Station Details screen anyway so that might fit in there?

**Comment by PanderMusubi** [comment]
Is backend API only, those apps will list Icerrr and user can choose there to enable or disable this option. 

You might need some parsing of "now playing" for the default stations you support/ship with Icerrr.

**Comment by PanderMusubi** [comment]
https://i.imgur.com/BUKogFM.png

**Comment by rejhgadellaa** [comment]
Hmm looks fairly easy:
https://github.com/tgwizard/sls/blob/master/Developer's%20API.md

Just send an intent with the info whenever now playing info changes (I already check for that)

Consider it wip :)

**Comment by rejhgadellaa** [comment]
![scrobbed](https://cloud.githubusercontent.com/assets/4703109/10140024/ecd6e220-6605-11e5-9a3d-3854b86ffa4e.PNG)

I think it's working. Will test some more and roll out with next release when it's stable :)

**Comment by PanderMusubi** [comment]
Screebshot looks nice! No problem to extract all required fields sich as artist, album and track from all streams?

**Comment by rejhgadellaa** [comment]
Well, depends on the station and how they put the now playing info in the stream. Because that doesn't support separate fields for those so I have to parse the string. Works for most but I have a feeling that intergalactic is going to be a mess because they put a LOT of info in there.

Album info is not included in the stream at all so I can't really add that. 

I had a look at some databases a while ago to search for info like that but haven't found a reliable one yet.

**Comment by PanderMusubi** [comment]
MusicBrains? Discogs?

**Comment by PanderMusubi** [comment]
Wikipedia?

**Comment by rejhgadellaa** [comment]
Echonest look good.. testing now
http://developer.echonest.com/docs/v4/song.html#search
