### ISSUE TITLE
Newest Iccerrr does not get past the main screen, unusable as of now 

### ISSUE THREAD

**Issue by Hilbert70** [rejhgadellaa/icerrr#242]
Hi,
Icerrr does not get past the screen with the headphones on my onda tablet  android 4.4.2

**Comment by rejhgadellaa** [comment]
Hi Hilbert,

That shouldn't happen.. can you tell me which version of Icerrr you are
running? (Settings > Apps > Downloaded > Icerrr > Somewhere at the top)?

I'll see if I can find your device in the logs I receive but this could be
difficult since I get a lot (and I have no read clear way to find a
specific devices quickly :))

Thanks for reporting!


*Roderick Gadellaa*
Designer, front-end developer, all things creative

T +31 6 5289 6036
E ik@rejh.nl
W www.rejh.nl

**Comment by rejhgadellaa** [comment]
Hi,

Just had a look, from what I can tell you're running 0.310 (0.31 in logs
because it's a float). Here's a log of what I believe is your device:
http://www.rejh.nl/icerrr/api/logs_users/html/b06df384863fa3ae6d39d3c33225b240_150ca70608a_a0d8.html

This is the relevant part:
2015-11-03 00:02:52     > Device: Android
2015-11-03 00:02:52     > Screen: 1024 x 695
2015-11-03 00:02:52     > Device Info: model: ONDA V989, platform: Android
4.4.2, cordova: 2.7.0
2015-11-03 00:02:52     > App version: 0.31
2015-11-03 00:02:52    TypeError: Cannot read property 'station_id' of null
    at Object.site.home.run_station_updates
(file:///android_asset/www/js/site.home.js:433:43)
    at file:///android_asset/www/js/site.home.js:252:69

It looks like the station data has become corrupt or at least something
happened to it that Icerrr is not ready to handle. That said, Icerrr is
currently at version 0.323 so I recommend an update. You can get it by
navigating to icerrr.rejh.nl, hitting Download (near the bottom) and
install the apk.

If the problem persists try to clear app data (Settings > Apps > Icerrr >
Clear data). If this still doesnt solve it please let me know.


*Roderick Gadellaa*
Designer, front-end developer, all things creative

T +31 6 5289 6036
E ik@rejh.nl
W www.rejh.nl

**Comment by Hilbert70** [comment]
The problem with version ,323 still persists even after clearing the cache and data. Restored version 0.310 and it is working again.

**Comment by rejhgadellaa** [comment]
Hi Hilbert,

My guess would be that I've changed some things since 0.310 that are no longer compatible with 0.323. I'll have a look and see if I can find the problem.

Just to be sure: you are not running any xposed modules or tinkered with advanced (custom rom) settings that might break things?

There's one more thing you could try (if you would): clear app data, remove the "Icerrr" folder on the phones storage (it should be in the root, if you're using Root Explorer or a similar file explorer it's something like /emulated/0/storage/Icerrr) and then try 0.323 again. I can imagine you don't feel like doing this though :)

Anyway, like I said: I'll have another look and also check what's been changed since 0.310:
https://github.com/rejhgadellaa/icerrr/wiki/Changelog
